In [75]:
import pandas as pd 
import numpy as np
df = pd.read_csv('../../world_death.csv')
df.head()
# governance.dtypes
# governance.describe(include="all")

,Year,Country Name,Country Code,Life Expectancy at birth (total years),Lifetime risk of maternal death (%),"Maternal mortality ratio (per 100,000 live births)","Mortality cauased by road traffic injury (per 100,000 population)","Mortality from CVD, cancer, diabetes or CRD between ages 30 and 70 (%)","Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)","Mortality rate attributed to unintentional poisoning (per 100,000 population)","Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)","Mortality rate, infant (per 1,000 live births)","Mortality rate, neonatal (per 1,000 live births)","Mortality rate, under-5 (per 1,000 live births)","Suicide mortality rate (per 100,000 population)","Intentional homicides (per 100,000 people)",GDP (current US$)
0,2016,Afghanistan,AFG,63.763,3.3309138614947,1194,14.8,35.6,211.1,1,13.9,51.3,39.3,67.5,4,6.5511634561,18116562464.9088
1,2017,Afghanistan,AFG,64.13,3.06359325193536,..,15.1,35.5,..,1.1,..,49.5,38.2,64.8,4.1,6.6784014409,18753469630.2586
2,2020,Afghanistan,AFG,..,..,..,..,..,..,..,..,45,35.2,58,..,..,20116137325.8206
3,2018,Afghanistan,AFG,64.486,..,..,14.2,35.4,..,0.9,..,47.9,37.2,62.3,4.1,6.6555611518,18053228578.8878
4,2019,Afghanistan,AFG,64.833,..,..,15.9,35.3,..,1,..,46.4,36.1,60.1,4.1,..,18799450742.7823

In [76]:
df=df.replace({'..':np.NaN}).fillna(value=np.NaN)#replace all cells with .. with None so that python can evaluate it as missing value
# df.fillna(value=np.NaN,inplace=True)
df.head()

,Year,Country Name,Country Code,Life Expectancy at birth (total years),Lifetime risk of maternal death (%),"Maternal mortality ratio (per 100,000 live births)","Mortality cauased by road traffic injury (per 100,000 population)","Mortality from CVD, cancer, diabetes or CRD between ages 30 and 70 (%)","Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)","Mortality rate attributed to unintentional poisoning (per 100,000 population)","Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)","Mortality rate, infant (per 1,000 live births)","Mortality rate, neonatal (per 1,000 live births)","Mortality rate, under-5 (per 1,000 live births)","Suicide mortality rate (per 100,000 population)","Intentional homicides (per 100,000 people)",GDP (current US$)
0,2016,Afghanistan,AFG,63.763,3.3309138614947,1194,14.8,35.6,211.1,1,13.9,51.3,39.3,67.5,4,6.5511634561,18116562464.9088
1,2017,Afghanistan,AFG,64.13,3.06359325193536,NaN,15.1,35.5,NaN,1.1,NaN,49.5,38.2,64.8,4.1,6.6784014409,18753469630.2586
2,2020,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45,35.2,58,NaN,NaN,20116137325.8206
3,2018,Afghanistan,AFG,64.486,NaN,NaN,14.2,35.4,NaN,0.9,NaN,47.9,37.2,62.3,4.1,6.6555611518,18053228578.8878
4,2019,Afghanistan,AFG,64.833,NaN,NaN,15.9,35.3,NaN,1,NaN,46.4,36.1,60.1,4.1,NaN,18799450742.7823

In [77]:
df.dtypes

Year                                                                                                            int64
Country Name                                                                                                   object
Country Code                                                                                                   object
Life Expectancy at birth (total years)                                                                         object
Lifetime risk of maternal death (%)                                                                            object
Maternal mortality ratio (per 100,000 live births)                                                             object
Mortality cauased by road traffic injury (per 100,000 population)                                              object
Mortality from CVD, cancer, diabetes or CRD between ages 30 and 70 (%)                                         object
Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)    object
Mortality rate attributed to unintentional poisoning (per 100,000 population)                                  object
Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)      object
Mortality rate, infant (per 1,000 live births)                                                                 object
Mortality rate, neonatal (per 1,000 live births)                                                               object
Mortality rate, under-5 (per 1,000 live births)                                                                object
Suicide mortality rate (per 100,000 population)                                                                object
Intentional homicides (per 100,000 people)                                                                     object
GDP (current US$)                                                                                              object
dtype: object

# changes data types accordingly

In [78]:
object_list = df.select_dtypes(include=['object']).columns.to_list()[2:]
# print(object_list)
df[object_list]=df[object_list].astype(float)
df.dtypes

Year                                                                                                             int64
Country Name                                                                                                    object
Country Code                                                                                                    object
Life Expectancy at birth (total years)                                                                         float64
Lifetime risk of maternal death (%)                                                                            float64
Maternal mortality ratio (per 100,000 live births)                                                             float64
Mortality cauased by road traffic injury (per 100,000 population)                                              float64
Mortality from CVD, cancer, diabetes or CRD between ages 30 and 70 (%)                                         float64
Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)    float64
Mortality rate attributed to unintentional poisoning (per 100,000 population)                                  float64
Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)      float64
Mortality rate, infant (per 1,000 live births)                                                                 float64
Mortality rate, neonatal (per 1,000 live births)                                                               float64
Mortality rate, under-5 (per 1,000 live births)                                                                float64
Suicide mortality rate (per 100,000 population)                                                                float64
Intentional homicides (per 100,000 people)                                                                     float64
GDP (current US$)                                                                                              float64
dtype: object

In [79]:
dic = {2016:0,2017:1,2018:2,2019:3,2020:4}
df['Age']=df['Year'].map(dic)
df

,Year,Country Name,Country Code,Life Expectancy at birth (total years),Lifetime risk of maternal death (%),"Maternal mortality ratio (per 100,000 live births)","Mortality cauased by road traffic injury (per 100,000 population)","Mortality from CVD, cancer, diabetes or CRD between ages 30 and 70 (%)","Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)","Mortality rate attributed to unintentional poisoning (per 100,000 population)","Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)","Mortality rate, infant (per 1,000 live births)","Mortality rate, neonatal (per 1,000 live births)","Mortality rate, under-5 (per 1,000 live births)","Suicide mortality rate (per 100,000 population)","Intentional homicides (per 100,000 people)",GDP (current US$),Age
0,2016,Afghanistan,AFG,63.763,3.330914,1194.0,14.8,35.6,211.1,1.0,13.9,51.3,39.3,67.5,4.0,6.551163,1.811656e+10,0
1,2017,Afghanistan,AFG,64.130,3.063593,NaN,15.1,35.5,NaN,1.1,NaN,49.5,38.2,64.8,4.1,6.678401,1.875347e+10,1
2,2020,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,35.2,58.0,NaN,NaN,2.011614e+10,4
3,2018,Afghanistan,AFG,64.486,NaN,NaN,14.2,35.4,NaN,0.9,NaN,47.9,37.2,62.3,4.1,6.655561,1.805323e+10,2
4,2019,Afghanistan,AFG,64.833,NaN,NaN,15.9,35.3,NaN,1.0,NaN,46.4,36.1,60.1,4.1,NaN,1.879945e+10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,2020,Zimbabwe,ZWE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.9,25.7,53.9,NaN,NaN,1.805117e+10,4
1326,2016,Zimbabwe,ZWE,60.294,1.911101,NaN,39.9,30.4,133.0,4.2,24.6,40.8,27.4,58.7,16.8,NaN,2.054868e+10,0
1327,2019,Zimbabwe,ZWE,61.490,NaN,NaN,41.2,28.4,NaN,3.5,NaN,38.1,26.2,54.2,14.1,NaN,1.928429e+10,3
1328,2017,Zimbabwe,ZWE,60.812,1.815294,NaN,40.1,29.3,NaN,3.7,NaN,39.9,27.0,57.0,15.0,NaN,1.758489e+10,1
1329,2018,Zimbabwe,ZWE,61.195,NaN,NaN,40.6,28.5,NaN,3.8,NaN,38.8,26.6,54.8,14.0,NaN,1.811554e+10,2

In [80]:
def fill_missing_values(group):
    value_columns = group.select_dtypes(include='number').columns

    for value_col in value_columns:
        values = group[value_col]
        known_values_mask = values.notnull()
        if known_values_mask.sum() > 0:  # If there is at least one known value
            if known_values_mask.sum() > 1:  # If there are more than one known values
                sorted_group = group.sort_values('Age')
                x_known = group.loc[known_values_mask, 'Age']
                y_known = group.loc[known_values_mask, value_col]
                a = (y_known.iloc[-1] - y_known.iloc[0]) / (x_known.iloc[-1] - x_known.iloc[0])
                b = y_known.iloc[0] - (a * x_known.iloc[0])

                missing_mask = values.isnull()
                x_missing = group.loc[missing_mask, 'Age']
                group.loc[missing_mask, value_col] = a * x_missing + b
            else:  # If there is only one known value
                known_value = values[known_values_mask].iloc[0]
                group[value_col].fillna(known_value, inplace=True)


    return group
final = df.reset_index().groupby('Country Name',group_keys=True).apply(fill_missing_values).reset_index(drop=True).drop('index',axis=1)
final

,Year,Country Name,Country Code,Life Expectancy at birth (total years),Lifetime risk of maternal death (%),"Maternal mortality ratio (per 100,000 live births)","Mortality cauased by road traffic injury (per 100,000 population)","Mortality from CVD, cancer, diabetes or CRD between ages 30 and 70 (%)","Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)","Mortality rate attributed to unintentional poisoning (per 100,000 population)","Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)","Mortality rate, infant (per 1,000 live births)","Mortality rate, neonatal (per 1,000 live births)","Mortality rate, under-5 (per 1,000 live births)","Suicide mortality rate (per 100,000 population)","Intentional homicides (per 100,000 people)",GDP (current US$),Age
0,2016,Afghanistan,AFG,63.763000,3.330914,1194.0,14.800000,35.6,211.1,1.0,13.9,51.3,39.3,67.5,4.000000,6.551163,1.811656e+10,0
1,2017,Afghanistan,AFG,64.130000,3.063593,1194.0,15.100000,35.5,211.1,1.1,13.9,49.5,38.2,64.8,4.100000,6.678401,1.875347e+10,1
2,2020,Afghanistan,AFG,65.189667,2.261631,1194.0,16.266667,35.2,211.1,1.0,13.9,45.0,35.2,58.0,4.133333,6.759959,2.011614e+10,4
3,2018,Afghanistan,AFG,64.486000,2.796273,1194.0,14.200000,35.4,211.1,0.9,13.9,47.9,37.2,62.3,4.100000,6.655561,1.805323e+10,2
4,2019,Afghanistan,AFG,64.833000,2.528952,1194.0,15.900000,35.3,211.1,1.0,13.9,46.4,36.1,60.1,4.100000,6.707760,1.879945e+10,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1325,2020,Zimbabwe,ZWE,62.096000,1.527874,NaN,41.300000,26.6,133.0,3.4,24.6,37.9,25.7,53.9,11.200000,NaN,1.805117e+10,4
1326,2016,Zimbabwe,ZWE,60.294000,1.911101,NaN,39.900000,30.4,133.0,4.2,24.6,40.8,27.4,58.7,16.800000,NaN,2.054868e+10,0
1327,2019,Zimbabwe,ZWE,61.490000,1.623681,NaN,41.200000,28.4,133.0,3.5,24.6,38.1,26.2,54.2,14.100000,NaN,1.928429e+10,3
1328,2017,Zimbabwe,ZWE,60.812000,1.815294,NaN,40.100000,29.3,133.0,3.7,24.6,39.9,27.0,57.0,15.000000,NaN,1.758489e+10,1
1329,2018,Zimbabwe,ZWE,61.195000,1.719488,NaN,40.600000,28.5,133.0,3.8,24.6,38.8,26.6,54.8,14.000000,NaN,1.811554e+10,2

In [81]:
final.sort_values(['Country Name', 'Age'],inplace=True)

In [82]:
final.fillna(value=0,inplace=True)

In [83]:
from ydata_profiling import  ProfileReport
correlations_options = {
    'pearson': {
        'correlation_threshold':0.5,
        'matrix':'dendrogram',
        'calculate':True,
        'numeric_only':True
    }
}

prof = ProfileReport(final,title='eda',explorative=True,dark_mode=True,minimal=True, correlations = correlations_options)
prof.to_file('output_file_cleaned.html')
# prof

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

c:\Users\amen\AppData\Local\Programs\Python\Python311\Lib\site-packages\ydata_profiling\model\pandas\correlations_pandas.py:36: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  return df.corr(method="pearson")

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [84]:
final.to_csv('world_death_cleaned.csv')